import test from 'node:test';import assert from 'node:assert/strict';
import {LeasedClient} from '../dist/persistence/client.js';
function store(){let revision=0, token='token',saved={},released=false;const calls=[];return {calls,get saved(){return saved;},request:async b=>{calls.push(b);if(b.action==='acquire')return {success:true,owner_token:token,attempt_id:'attempt',revision,data:saved};if(b.owner_token!==token)return {success:false,reason:'conflict'};if(b.action==='save'){assert.equal(b.revision,revision);saved=structuredClone(b.data);revision++;}if(b.action==='release')released=true;return {success:true,revision};},get released(){return released;}};}
test('atomic session/meta/stats checkpoint and release',async()=>{const db=store(),c=new LeasedClient(db.request);await c.acquire();c.mutate(s=>s.inputLetter('A'));const saved=await c.checkpoint();assert.deepEqual(db.saved,saved);assert(saved.game&&saved.meta&&saved.stats);await c.release();assert(db.released);assert(!c.active);});
test('queued writes use successive revisions',async()=>{const db=store(),c=new LeasedClient(db.request);await c.acquire();await Promise.all([c.checkpoint(),c.checkpoint()]);await c.release();assert.deepEqual(db.calls.filter(x=>x.action==='save').map(x=>x.revision),[0,1,2]);});
test('release freezes input immediately and is idempotent',async()=>{const db=store(),c=new LeasedClient(db.request);await c.acquire();const a=c.release();assert.throws(()=>c.mutate(s=>s.inputLetter('A')));assert.equal(c.release(),a);await a;assert.equal(db.calls.filter(x=>x.action==='release').length,1);});
test('save conflict suspends writer without releasing successor',async()=>{const db=store(),c=new LeasedClient(b=>b.action==='save'?Promise.resolve({success:false,reason:'conflict'}):db.request(b));await c.acquire();await assert.rejects(c.checkpoint());assert(!c.active);assert.equal(c.error,'conflict');assert.throws(()=>c.mutate(s=>s.newGame()));assert(!db.released);c.abandon();});
test('invalid stored snapshot releases acquired lease',async()=>{const db=store(),c=new LeasedClient(async b=>{const r=await db.request(b);return b.action==='acquire'?{...r,data:{invalid:true}}:r;});await assert.rejects(c.acquire());assert(db.released);assert(!c.active);});
test('handoff completes revealing and stats in same save',async()=>{const db=store(),c=new LeasedClient(db.request);await c.acquire();c.mutate(s=>{for(const l of s.getState().answer)s.inputLetter(l);s.submit();});assert.equal(c.session.getState().status,'revealing');const saved=await c.release();assert.equal(saved.game.status,'won');assert.equal(saved.stats.overall.gamesPlayed,1);assert.equal(db.saved.stats.recentGames[0].id,saved.game.id);});
