<?php

declare(strict_types=1);

use BinktermPHP\NativeDoorManager;
use PHPUnit\Framework\TestCase;

/**
 * M1: the Tristam Island interactive-fiction native door.
 *
 * Tristam Island is a CC0 parser adventure by Hugo Labrande, run through the
 * (unmodified, sysop-installed) Frotz Z-machine interpreter. The whole
 * integration is a manifest, a tiny wrapper (run.sh) and the read-only story
 * file — no BinktermPHP platform source is touched.
 *
 * These tests assert the manifest parses against the real native-door schema,
 * identifies the game correctly, keeps the door authenticated-only, routes
 * launches through run.sh, and that the bundled story + licence material match
 * the author's canonical CC0 distribution.
 */
final class TristamManifestTest extends TestCase
{
    /** sha256 of tristam-en.z3 (Release 5 / serial 220830) from the author's
     *  canonical repository, https://github.com/hlabrand/tristam-island (main). */
    private const STORY_SHA256 = 'd178078af04528be0dbc3bb41743ca44d5436b78f10e8ca99e95fddc0a4c2b0f';

    private string $doorDir;
    /** @var array<string,mixed> */
    private array $rawManifest;

    protected function setUp(): void
    {
        $root = dirname(__DIR__, 2);
        $this->doorDir = $root . '/native-doors/doors/tristam';

        $manifestPath = $this->doorDir . '/nativedoor.json';
        self::assertFileExists($manifestPath, 'tristam manifest is missing');

        $decoded = json_decode((string)file_get_contents($manifestPath), true);
        self::assertIsArray($decoded, 'tristam manifest is not valid JSON');
        $this->rawManifest = $decoded;
    }

    public function testManifestParsesAgainstTheNativeDoorScanner(): void
    {
        // getDoor() returns null on any schema violation the scanner rejects.
        $door = (new NativeDoorManager())->getDoor('tristam');

        self::assertIsArray($door, 'NativeDoorManager could not parse the tristam manifest');
        self::assertSame('tristam', $door['door_id']);
        self::assertSame('nativedoor', $door['type']);
        self::assertSame('run.sh', $door['executable']);
    }

    public function testManifestIdentifiesTristamIsland(): void
    {
        $door = (new NativeDoorManager())->getDoor('tristam');

        self::assertSame('Tristam Island', $door['name']);
        self::assertSame('TRISTAM', $door['short_name']);
        self::assertSame('Hugo Labrande', $door['author']);
        self::assertSame('Tristam Island', $this->rawManifest['game']['name']);
        self::assertContains('Interactive Fiction', $this->rawManifest['game']['genre'] ?? []);
    }

    public function testManifestIsASinglePlayerGameExperience(): void
    {
        self::assertSame('game', $this->rawManifest['experience']['category'] ?? null);
        self::assertFalse((bool)($this->rawManifest['experience']['multiplayer'] ?? true));
        self::assertFalse((bool)($this->rawManifest['experience']['participant_messaging'] ?? true));
    }

    public function testDoorIsNotAdminOnlyButDeniesAnonymousLaunch(): void
    {
        $door = (new NativeDoorManager())->getDoor('tristam');

        // Open to any registered member...
        self::assertFalse($door['admin_only'], 'tristam should not be admin-only');
        // ...but never to anonymous guests. The wrapper enforces this too.
        self::assertFalse(
            (bool)($door['config']['allow_anonymous'] ?? false),
            'tristam must not permit anonymous launches'
        );
    }

    public function testLaunchGoesThroughTheWrapperInRawUtf8Mode(): void
    {
        $launch = (string)($this->rawManifest['door']['launch_command'] ?? '');

        self::assertStringContainsString('run.sh', $launch);
        self::assertFileExists($this->doorDir . '/run.sh');

        self::assertSame('raw', $this->rawManifest['door']['terminal_mode'] ?? null);
        self::assertSame('utf8', $this->rawManifest['door']['output_encoding'] ?? null);
        // Plain text story; no ANSI is generated by the interpreter.
        self::assertFalse((bool)($this->rawManifest['door']['ansi_required'] ?? true));
    }

    public function testBundledStoryFileMatchesTheAuthorsCc0Distribution(): void
    {
        $story = $this->doorDir . '/story/tristam-en.z3';
        self::assertFileExists($story, 'the Z-machine story file is missing');
        self::assertSame(
            self::STORY_SHA256,
            hash_file('sha256', $story),
            'tristam-en.z3 does not match the known-good CC0 release from the author'
        );

        // Z-machine v3 header: byte 0 is the version number.
        self::assertSame(3, ord((string)file_get_contents($story, false, null, 0, 1)));
    }

    public function testLicenceMaterialIsThePublicDomainDedication(): void
    {
        $license = $this->doorDir . '/LICENSE';
        self::assertFileExists($license, 'the CC0 LICENSE file is missing');

        $text = (string)file_get_contents($license);
        self::assertStringContainsString('CC0 1.0 Universal', $text);
        self::assertStringContainsString('waives, abandons, and surrenders', $text);

        // The door README must document provenance and the exact story hash so a
        // future sysop can re-verify it against the author's repository.
        $readme = (string)file_get_contents($this->doorDir . '/README.md');
        self::assertStringContainsString('CC0', $readme);
        self::assertStringContainsString(self::STORY_SHA256, $readme);
        self::assertStringContainsString('hlabrand/tristam-island', $readme);
        // Frotz is GPL and NOT bundled — the README must be honest about that.
        self::assertStringContainsString('GPL', $readme);
        self::assertMatchesRegularExpression('/not\s+bundled|installed by the sysop/i', $readme);
    }
}
